services:
  # Backend service
  - type: web
    name: tracehost-backend
    env: python
    region: oregon
    buildCommand: |
      cd Backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: cd Backend && gunicorn website_checker.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "tracehost-backend.onrender.com,tracehost.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://tracehost.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ALLOW_ALL_ORIGINS
        value: false
      - key: IPINFO_API_KEY
        sync: false
      - key: SHODAN_API_KEY
        sync: false
      - key: SECURITY_TRAILS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true

  # Frontend service
  - type: web
    name: tracehost
    env: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: ./Frontend/out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://tracehost-backend.onrender.com/api
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://tracehost-backend.onrender.com
      - key: NEXT_PUBLIC_FRONTEND_URL
        value: https://tracehost.onrender.com
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
    autoDeploy: true 