# Generated by Django 5.1.1 on 2025-02-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('scan_result', models.TextField(blank=True, null=True)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('registrant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registrant_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('subdomains', models.JSONField(blank=True, null=True)),
                ('historical_dns', models.JSONField(blank=True, null=True)),
                ('ssl_info', models.JSONField(blank=True, null=True)),
                ('shodan_info', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_link', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
    ]
