# Generated by Django 5.1.1 on 2025-02-21 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainscan',
            name='scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
