# Generated by Django 4.2.10 on 2025-03-20 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_alter_domainscan_scan_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainscan',
            options={'ordering': ['-scan_date'], 'verbose_name': 'Domain Scan', 'verbose_name_plural': 'Domain Scans'},
        ),
        migrations.RenameField(
            model_name='domainscan',
            old_name='updated_date',
            new_name='last_flagged_date',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='historical_dns',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='location',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='location_link',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='registrant_name',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='registrant_organization',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='shodan_info',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='ssl_info',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='subdomains',
        ),
        migrations.AddField(
            model_name='domainscan',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='last_scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='domain',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='scan_result',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='domainscan',
            index=models.Index(fields=['domain'], name='checker_dom_domain_52bd30_idx'),
        ),
        migrations.AddIndex(
            model_name='domainscan',
            index=models.Index(fields=['is_suspicious'], name='checker_dom_is_susp_581c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='domainscan',
            index=models.Index(fields=['is_flagged'], name='checker_dom_is_flag_4133b9_idx'),
        ),
        migrations.AddIndex(
            model_name='domainscan',
            index=models.Index(fields=['scan_date'], name='checker_dom_scan_da_289d69_idx'),
        ),
        migrations.AddIndex(
            model_name='domainscan',
            index=models.Index(fields=['risk_score'], name='checker_dom_risk_sc_537143_idx'),
        ),
    ]
